-- Create CDMTRADES table for CDM BusinessEvent storage
CREATE TABLE IF NOT EXISTS CDMTRADES (
    ID VARCHAR(50) PRIMARY KEY,
    ACCOUNTID INTEGER,
    CREATED TIMESTAMP,
    UPDATED TIMESTAMP,
    SECURITY VARCHAR(15),
    SIDE VARCHAR(10),
    QUANTITY INTEGER,
    STATE VARCHAR(20),
    CDMTRADEOBJ VARCHAR(2000)
);

-- Insert a test record to verify table creation
INSERT INTO CDMTRADES (ID, ACCOUNTID, CREATED, UPDATED, SECURITY, SIDE, QUANTITY, STATE, CDMTRADEOBJ) 
VALUES ('TEST-001', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'AAPL', 'Buy', 100, 'Settled', '{"test": "cdm_data"}');

-- Show table structure
SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CDMTRADES';

-- Show test data
SELECT * FROM CDMTRADES;