-- CDM Table Creation Script
CREATE TABLE IF NOT EXISTS CDMTRADES (
    ID VARCHAR(50) PRIMARY KEY,
    ACCOUNTID INTEGER,
    CREATED TIMESTAMP,
    UPDATED TIMESTAMP,
    SECURITY VARCHAR(15),
    SIDE VARCHAR(10),
    QUANTITY INTEGER,
    STATE VARCHAR(20),
    CDMTRADEOBJ VARCHAR(2000)
);